<?php

namespace App\Enums;

enum Country: string
{
    case AFG = 'AF';
    case ALB = 'AL';
    case DZA = 'DZ';
    case ASM = 'AS';
    case AND = 'AD';
    case AGO = 'AO';
    case AIA = 'AI';
    case ATA = 'AQ';
    case ATG = 'AG';
    case ARG = 'AR';
    case ARM = 'AM';
    case ABW = 'AW';
    case AUS = 'AU';
    case AUT = 'AT';
    case AZE = 'AZ';
    case BHS = 'BS';
    case BHR = 'BH';
    case BGD = 'BD';
    case BRB = 'BB';
    case BLR = 'BY';
    case BEL = 'BE';
    case BLZ = 'BZ';
    case BEN = 'BJ';
    case BMU = 'BM';
    case BTN = 'BT';
    case BOL = 'BO';
    case BES = 'BQ';
    case BIH = 'BA';
    case BWA = 'BW';
    case BVT = 'BV';
    case BRA = 'BR';
    case IOT = 'IO';
    case BRN = 'BN';
    case BGR = 'BG';
    case BFA = 'BF';
    case BDI = 'BI';
    case CPV = 'CV';
    case KHM = 'KH';
    case CMR = 'CM';
    case CAN = 'CA';
    case CYM = 'KY';
    case CAF = 'CF';
    case TCD = 'TD';
    case CHL = 'CL';
    case CHN = 'CN';
    case CXR = 'CX';
    case CCK = 'CC';
    case COL = 'CO';
    case COM = 'KM';
    case COD = 'CD';
    case COG = 'CG';
    case COK = 'CK';
    case CRI = 'CR';
    case HRV = 'HR';
    case CUB = 'CU';
    case CUW = 'CW';
    case CYP = 'CY';
    case CZE = 'CZ';
    case CIV = 'CI';
    case DNK = 'DK';
    case DJI = 'DJ';
    case DMA = 'DM';
    case DOM = 'DO';
    case ECU = 'EC';
    case EGY = 'EG';
    case SLV = 'SV';
    case GNQ = 'GQ';
    case ERI = 'ER';
    case EST = 'EE';
    case SWZ = 'SZ';
    case ETH = 'ET';
    case FLK = 'FK';
    case FRO = 'FO';
    case FJI = 'FJ';
    case FIN = 'FI';
    case FRA = 'FR';
    case GUF = 'GF';
    case PYF = 'PF';
    case ATF = 'TF';
    case GAB = 'GA';
    case GMB = 'GM';
    case GEO = 'GE';
    case DEU = 'DE';
    case GHA = 'GH';
    case GIB = 'GI';
    case GRC = 'GR';
    case GRL = 'GL';
    case GRD = 'GD';
    case GLP = 'GP';
    case GUM = 'GU';
    case GTM = 'GT';
    case GGY = 'GG';
    case GIN = 'GN';
    case GNB = 'GW';
    case GUY = 'GY';
    case HTI = 'HT';
    case HMD = 'HM';
    case VAT = 'VA';
    case HND = 'HN';
    case HKG = 'HK';
    case HUN = 'HU';
    case ISL = 'IS';
    case IND = 'IN';
    case IDN = 'ID';
    case IRN = 'IR';
    case IRQ = 'IQ';
    case IRL = 'IE';
    case IMN = 'IM';
    case ISR = 'IL';
    case ITA = 'IT';
    case JAM = 'JM';
    case JPN = 'JP';
    case JEY = 'JE';
    case JOR = 'JO';
    case KAZ = 'KZ';
    case KEN = 'KE';
    case KIR = 'KI';
    case XKS = 'XK';
    case PRK = 'KP';
    case KOR = 'KR';
    case KWT = 'KW';
    case KGZ = 'KG';
    case LAO = 'LA';
    case LVA = 'LV';
    case LBN = 'LB';
    case LSO = 'LS';
    case LBR = 'LR';
    case LBY = 'LY';
    case LIE = 'LI';
    case LTU = 'LT';
    case LUX = 'LU';
    case MAC = 'MO';
    case MKD = 'MK';
    case MDG = 'MG';
    case MWI = 'MW';
    case MYS = 'MY';
    case MDV = 'MV';
    case MLI = 'ML';
    case MLT = 'MT';
    case MHL = 'MH';
    case MTQ = 'MQ';
    case MRT = 'MR';
    case MUS = 'MU';
    case MYT = 'YT';
    case MEX = 'MX';
    case FSM = 'FM';
    case MDA = 'MD';
    case MCO = 'MC';
    case MNG = 'MN';
    case MNE = 'ME';
    case MSR = 'MS';
    case MAR = 'MA';
    case MOZ = 'MZ';
    case MMR = 'MM';
    case NAM = 'NA';
    case NRU = 'NR';
    case NPL = 'NP';
    case NLD = 'NL';
    case NCL = 'NC';
    case NZL = 'NZ';
    case NIC = 'NI';
    case NER = 'NE';
    case NGA = 'NG';
    case NIU = 'NU';
    case NFK = 'NF';
    case MNP = 'MP';
    case NOR = 'NO';
    case OMN = 'OM';
    case PAK = 'PK';
    case PLW = 'PW';
    case PSE = 'PS';
    case PAN = 'PA';
    case PNG = 'PG';
    case PRY = 'PY';
    case PER = 'PE';
    case PHL = 'PH';
    case PCN = 'PN';
    case POL = 'PL';
    case PRT = 'PT';
    case PRI = 'PR';
    case QAT = 'QA';
    case ROU = 'RO';
    case RUS = 'RU';
    case RWA = 'RW';
    case REU = 'RE';
    case BLM = 'BL';
    case SHN = 'SH';
    case KNA = 'KN';
    case LCA = 'LC';
    case MAF = 'MF';
    case SPM = 'PM';
    case VCT = 'VC';
    case WSM = 'WS';
    case SMR = 'SM';
    case STP = 'ST';
    case SAU = 'SA';
    case SEN = 'SN';
    case SRB = 'RS';
    case SYC = 'SC';
    case SLE = 'SL';
    case SGP = 'SG';
    case SXM = 'SX';
    case SVK = 'SK';
    case SVN = 'SI';
    case SLB = 'SB';
    case SOM = 'SO';
    case ZAF = 'ZA';
    case SGS = 'GS';
    case SSD = 'SS';
    case ESP = 'ES';
    case LKA = 'LK';
    case SDN = 'SD';
    case SUR = 'SR';
    case SJM = 'SJ';
    case SWE = 'SE';
    case CHE = 'CH';
    case SYR = 'SY';
    case TWN = 'TW';
    case TJK = 'TJ';
    case TZA = 'TZ';
    case THA = 'TH';
    case TLS = 'TL';
    case TGO = 'TG';
    case TKL = 'TK';
    case TON = 'TO';
    case TTO = 'TT';
    case TUN = 'TN';
    case TUR = 'TR';
    case TKM = 'TM';
    case TCA = 'TC';
    case TUV = 'TV';
    case UGA = 'UG';
    case UKR = 'UA';
    case ARE = 'AE';
    case GBR = 'GB';
    case UMI = 'UM';
    case USA = 'US';
    case URY = 'UY';
    case UZB = 'UZ';
    case VUT = 'VU';
    case VEN = 'VE';
    case VNM = 'VN';
    case VGB = 'VG';
    case VIR = 'VI';
    case WLF = 'WF';
    case ESH = 'EH';
    case YEM = 'YE';
    case ZMB = 'ZM';
    case ZWE = 'ZW';
    case ALA = 'AX';

    public static function name($country): string
    {
        return match ($country) {
            self::AFG => 'Afghanistan',
            self::ALB => 'Albania',
            self::DZA => 'Algeria',
            self::ASM => 'American Samoa',
            self::AND => 'Andorra',
            self::AGO => 'Angola',
            self::AIA => 'Anguilla',
            self::ATA => 'Antarctica',
            self::ATG => 'Antigua and Barbuda',
            self::ARG => 'Argentina',
            self::ARM => 'Armenia',
            self::ABW => 'Aruba',
            self::AUS => 'Australia',
            self::AUT => 'Austria',
            self::AZE => 'Azerbaijan',
            self::BHS => 'Bahamas (the)',
            self::BHR => 'Bahrain',
            self::BGD => 'Bangladesh',
            self::BRB => 'Barbados',
            self::BLR => 'Belarus',
            self::BEL => 'Belgium',
            self::BLZ => 'Belize',
            self::BEN => 'Benin',
            self::BMU => 'Bermuda',
            self::BTN => 'Bhutan',
            self::BOL => 'Bolivia (Plurinational State of)',
            self::BES => 'Bonaire, Sint Eustatius and Saba',
            self::BIH => 'Bosnia and Herzegovina',
            self::BWA => 'Botswana',
            self::BVT => 'Bouvet Island',
            self::BRA => 'Brazil',
            self::IOT => 'British Indian Ocean Territory (the)',
            self::BRN => 'Brunei Darussalam',
            self::BGR => 'Bulgaria',
            self::BFA => 'Burkina Faso',
            self::BDI => 'Burundi',
            self::CPV => 'Cabo Verde',
            self::KHM => 'Cambodia',
            self::CMR => 'Cameroon',
            self::CAN => 'Canada',
            self::CYM => 'Cayman Islands (the)',
            self::CAF => 'Central African Republic (the)',
            self::TCD => 'Chad',
            self::CHL => 'Chile',
            self::CHN => 'China',
            self::CXR => 'Christmas Island',
            self::CCK => 'Cocos (Keeling) Islands (the)',
            self::COL => 'Colombia',
            self::COM => 'Comoros (the)',
            self::COD => 'Congo (the Democratic Republic of the)',
            self::COG => 'Congo (the)',
            self::COK => 'Cook Islands (the)',
            self::CRI => 'Costa Rica',
            self::HRV => 'Croatia',
            self::CUB => 'Cuba',
            self::CUW => 'Curaçao',
            self::CYP => 'Cyprus',
            self::CZE => 'Czechia',
            self::CIV => "Côte d'Ivoire",
            self::DNK => 'Denmark',
            self::DJI => 'Djibouti',
            self::DMA => 'Dominica',
            self::DOM => 'Dominican Republic (the)',
            self::ECU => 'Ecuador',
            self::EGY => 'Egypt',
            self::SLV => 'El Salvador',
            self::GNQ => 'Equatorial Guinea',
            self::ERI => 'Eritrea',
            self::EST => 'Estonia',
            self::SWZ => 'Eswatini',
            self::ETH => 'Ethiopia',
            self::FLK => 'Falkland Islands (the) [Malvinas]',
            self::FRO => 'Faroe Islands (the)',
            self::FJI => 'Fiji',
            self::FIN => 'Finland',
            self::FRA => 'France',
            self::GUF => 'French Guiana',
            self::PYF => 'French Polynesia',
            self::ATF => 'French Southern Territories (the)',
            self::GAB => 'Gabon',
            self::GMB => 'Gambia (the)',
            self::GEO => 'Georgia',
            self::DEU => 'Germany',
            self::GHA => 'Ghana',
            self::GIB => 'Gibraltar',
            self::GRC => 'Greece',
            self::GRL => 'Greenland',
            self::GRD => 'Grenada',
            self::GLP => 'Guadeloupe',
            self::GUM => 'Guam',
            self::GTM => 'Guatemala',
            self::GGY => 'Guernsey',
            self::GIN => 'Guinea',
            self::GNB => 'Guinea-Bissau',
            self::GUY => 'Guyana',
            self::HTI => 'Haiti',
            self::HMD => 'Heard Island and McDonald Islands',
            self::VAT => 'Holy See (the)',
            self::HND => 'Honduras',
            self::HKG => 'Hong Kong',
            self::HUN => 'Hungary',
            self::ISL => 'Iceland',
            self::IND => 'India',
            self::IDN => 'Indonesia',
            self::IRN => 'Iran (Islamic Republic of)',
            self::IRQ => 'Iraq',
            self::IRL => 'Ireland',
            self::IMN => 'Isle of Man',
            self::ISR => 'Israel',
            self::ITA => 'Italy',
            self::JAM => 'Jamaica',
            self::JPN => 'Japan',
            self::JEY => 'Jersey',
            self::JOR => 'Jordan',
            self::KAZ => 'Kazakhstan',
            self::KEN => 'Kenya',
            self::KIR => 'Kiribati',
            self::XKS => 'Kosovo',
            self::PRK => "Korea (the Democratic People's Republic of)",
            self::KOR => 'Korea (the Republic of)',
            self::KWT => 'Kuwait',
            self::KGZ => 'Kyrgyzstan',
            self::LAO => "Lao People's Democratic Republic (the)",
            self::LVA => 'Latvia',
            self::LBN => 'Lebanon',
            self::LSO => 'Lesotho',
            self::LBR => 'Liberia',
            self::LBY => 'Libya',
            self::LIE => 'Liechtenstein',
            self::LTU => 'Lithuania',
            self::LUX => 'Luxembourg',
            self::MAC => 'Macao',
            self::MKD => 'Macedonia',
            self::MDG => 'Madagascar',
            self::MWI => 'Malawi',
            self::MYS => 'Malaysia',
            self::MDV => 'Maldives',
            self::MLI => 'Mali',
            self::MLT => 'Malta',
            self::MHL => 'Marshall Islands (the)',
            self::MTQ => 'Martinique',
            self::MRT => 'Mauritania',
            self::MUS => 'Mauritius',
            self::MYT => 'Mayotte',
            self::MEX => 'Mexico',
            self::FSM => 'Micronesia (Federated States of)',
            self::MDA => 'Moldova (the Republic of)',
            self::MCO => 'Monaco',
            self::MNG => 'Mongolia',
            self::MNE => 'Montenegro',
            self::MSR => 'Montserrat',
            self::MAR => 'Morocco',
            self::MOZ => 'Mozambique',
            self::MMR => 'Myanmar',
            self::NAM => 'Namibia',
            self::NRU => 'Nauru',
            self::NPL => 'Nepal',
            self::NLD => 'Netherlands (the)',
            self::NCL => 'New Caledonia',
            self::NZL => 'New Zealand',
            self::NIC => 'Nicaragua',
            self::NER => 'Niger (the)',
            self::NGA => 'Nigeria',
            self::NIU => 'Niue',
            self::NFK => 'Norfolk Island',
            self::MNP => 'Northern Mariana Islands (the)',
            self::NOR => 'Norway',
            self::OMN => 'Oman',
            self::PAK => 'Pakistan',
            self::PLW => 'Palau',
            self::PSE => 'Palestine, State of',
            self::PAN => 'Panama',
            self::PNG => 'Papua New Guinea',
            self::PRY => 'Paraguay',
            self::PER => 'Peru',
            self::PHL => 'Philippines (the)',
            self::PCN => 'Pitcairn',
            self::POL => 'Poland',
            self::PRT => 'Portugal',
            self::PRI => 'Puerto Rico',
            self::QAT => 'Qatar',
            self::ROU => 'Romania',
            self::RUS => 'Russian Federation (the)',
            self::RWA => 'Rwanda',
            self::REU => 'Réunion',
            self::BLM => 'Saint Barthélemy',
            self::SHN => 'Saint Helena, Ascension and Tristan da Cunha',
            self::KNA => 'Saint Kitts and Nevis',
            self::LCA => 'Saint Lucia',
            self::MAF => 'Saint Martin (French part)',
            self::SPM => 'Saint Pierre and Miquelon',
            self::VCT => 'Saint Vincent and the Grenadines',
            self::WSM => 'Samoa',
            self::SMR => 'San Marino',
            self::STP => 'Sao Tome and Principe',
            self::SAU => 'Saudi Arabia',
            self::SEN => 'Senegal',
            self::SRB => 'Serbia',
            self::SYC => 'Seychelles',
            self::SLE => 'Sierra Leone',
            self::SGP => 'Singapore',
            self::SXM => 'Sint Maarten (Dutch part)',
            self::SVK => 'Slovakia',
            self::SVN => 'Slovenia',
            self::SLB => 'Solomon Islands',
            self::SOM => 'Somalia',
            self::ZAF => 'South Africa',
            self::SGS => 'South Georgia and the South Sandwich Islands',
            self::SSD => 'South Sudan',
            self::ESP => 'Spain',
            self::LKA => 'Sri Lanka',
            self::SDN => 'Sudan (the)',
            self::SUR => 'Suriname',
            self::SJM => 'Svalbard and Jan Mayen',
            self::SWE => 'Sweden',
            self::CHE => 'Switzerland',
            self::SYR => 'Syrian Arab Republic',
            self::TWN => 'Taiwan (Province of China)',
            self::TJK => 'Tajikistan',
            self::TZA => 'Tanzania, United Republic of',
            self::THA => 'Thailand',
            self::TLS => 'Timor-Leste',
            self::TGO => 'Togo',
            self::TKL => 'Tokelau',
            self::TON => 'Tonga',
            self::TTO => 'Trinidad and Tobago',
            self::TUN => 'Tunisia',
            self::TUR => 'Turkey',
            self::TKM => 'Turkmenistan',
            self::TCA => 'Turks and Caicos Islands (the)',
            self::TUV => 'Tuvalu',
            self::UGA => 'Uganda',
            self::UKR => 'Ukraine',
            self::ARE => 'United Arab Emirates (the)',
            self::GBR => 'United Kingdom of Great Britain and Northern Ireland (the)',
            self::UMI => 'United States Minor Outlying Islands (the)',
            self::USA => 'United States of America (the)',
            self::URY => 'Uruguay',
            self::UZB => 'Uzbekistan',
            self::VUT => 'Vanuatu',
            self::VEN => 'Venezuela (Bolivarian Republic of)',
            self::VNM => 'Viet Nam',
            self::VGB => 'Virgin Islands (British)',
            self::VIR => 'Virgin Islands (U.S.)',
            self::WLF => 'Wallis and Futuna',
            self::ESH => 'Western Sahara',
            self::YEM => 'Yemen',
            self::ZMB => 'Zambia',
            self::ZWE => 'Zimbabwe',
            self::ALA => 'Åland Islands',
        };
    }
}
